#!/bin/bash 


################################################################################################
echo "systemctl start network
sudo wget  https://download.virtualbox.org/virtualbox/NUMBER/VBoxGuestAdditions_NUMBER.iso
sudo mkdir /mnt/iso
sudo mount -t iso9660 -o loop VBoxGuestAdditions_NUMBER.iso /mnt/iso/
sudo bash /mnt/iso/VBoxLinuxAdditions.run	
echo "" > /etc/rc.d/rc.local
sudo rm -rf /installvbox.sh
sudo reboot" > /installvbox.sh


#author Farkhod Sadykov
